# Generated by Django 5.2.3 on 2025-06-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
