# Generated by Django 5.2.3 on 2025-06-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
