# Generated by Django 5.2.3 on 2025-06-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_product_seller_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
