# Generated by Django 5.2.3 on 2025-06-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_thread_order_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
