# Generated by Django 5.2.3 on 2025-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='competition_thumbnail',
            field=models.ImageField(default='site/', upload_to='site/'),
        ),
    ]
