# Generated by Django 5.2.3 on 2025-07-03 13:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_sitesettings_competition_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='competition_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='competition_finish',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='competition_start',
            field=models.DateField(null=True),
        ),
    ]
