# Generated by Django 5.2.3 on 2025-07-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_sitesettings_competition_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pay_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ImageField(upload_to='payments/')),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('review', 'Review'), ('completed', 'Completed'), ('cancel', 'Cancel')], max_length=255)),
                ('card_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
