# Generated by Django 5.2.3 on 2025-07-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_payment_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(null=True, upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('review', 'Review'), ('completed', 'Completed'), ('cancel', 'Cancel')], default='review', max_length=255),
        ),
    ]
