# Generated by Django 5.2.3 on 2025-07-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
