# Generated by Django 5.2.3 on 2025-07-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_alter_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('deliver', 'Deliver')], default='deliver', max_length=255),
        ),
    ]
