# Generated by Django 5.2.3 on 2025-07-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('deliver', 'Deliver'), ('user', 'User')], default='user', max_length=255),
        ),
    ]
