# Generated by Django 5.2.3 on 2025-07-03 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
