# Generated by Django 5.2.3 on 2025-07-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_order_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hold',
            field=models.BooleanField(default=False),
        ),
    ]
