# Generated by Django 5.2.3 on 2025-07-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_order_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
